server.port: 8080

# PostgreSQL DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/jwt_security
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Hikari Connection Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# for k6
management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.export.prometheus.enabled=true
